language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - cd client
install:
  npm run build
before_script:
  - cd ..
script:
  - npm run deploy
after_success:
  - npm run start